name = "1.21.1 Serverpack"
author = "oskardotglobal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc2d206c7f5cf80007094da9da97791d9ba72964919b807fe906b2d0b9bd0137"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "world/datapacks"
