name = "1.21.1 Serverpack"
author = "oskardotglobal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e72f7d7b61d1e6dc9c12b6525a7493b303f857ca7b8a08d3257b661e5afc0825"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
datapack-folder = "world/datapacks"
