name = "1.21.1 Serverpack"
author = "oskardotglobal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ef849897e160cdbe6a39edcbf53849eee52c2c248947814ca5c283688d46423"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "world/datapacks"
