name = "1.21.1 Serverpack"
author = "oskardotglobal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cf31440e00602c892a3c1d0b53154051bbc165303f13a46f366e243707662d4"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
